### ISSUE TITLE
Divide operator does not deliver expected result when applied on one value only

### ISSUE THREAD

**Issue by patmonfort** [jamsesso/json-logic-java#11]
Hello, 
Trying the following rule {"/":[8]} returns null on standard JSON logic (http://jsonlogic.com/play.html) but does return the value itself using the lib. (v1.0.2).
Can you please check the 'evaluate' method of "MathExpression" and considering a special case for the '/' operator when the array of arguments contains one element?
Or maybe this one is a fix to be provided in json logic 'official' js lib itself.

**Comment by jamsesso** [comment]
@patmonfort thanks for helping me find some inconsistencies between the Javascript implementation and this one - can you create a list of everything you find instead of creating one-off issues? I will fix them all as part of a single PR.

**Comment by patmonfort** [comment]
@jamsesso Hello, of course, please find the list below. 
The lib is very helpfull, thanks for this job. Let me know if you need additional information.

* '/' operator
  - described above.

* 'in' operator
  - The following rule returns the exception 'in expects the second argument to be either a string or an array", it returns false using [jsonLogic](http://jsonlogic.com/play.html)
    Rule : { "in" : ["abc", 3] }

  - The following rule return the exception 'in expects exactly 2 arguments', should returns false according to json logic
    Rule: { "in" : ["Spring"] }

* 'Number' are considered alsways as Double in java lib (may impact custom operators)
  - The rule { "var" : "x" } with data { "x" : 1 } returns the double (1.0), the java lib convert Int in Double internally, Javascript lib considers 1 and 1.0 as Int.

**Comment by jamsesso** [comment]
Thanks @patmonfort. I'll take a look at these issues. Your last point about conversion to Double is done by design. In Javascript there are no integers, so this library attempts to convert all Integer inputs to Doubles to mimmic that behaviour. Without it, other bugs pop up.

**Comment by patmonfort** [comment]
Hello @jamsesso , this work is very appreciated, thanks for this development. That's understood for the issue around number/interger/double. I'll check when updates are available, let me know if you think I could help.

**Comment by jamsesso** [comment]
@patmonfort I've updated the PR - can you verify?

**Comment by patmonfort** [comment]
@jamsesso hello, that's perfect, many thanks.
