### ISSUE TITLE
First argument to "SOME" must be a valid array

### ISSUE THREAD

**Issue by rashhvarikuti** [jamsesso/json-logic-java#14]
@jamsesso I am using some in below rule to compare data:

here is the rule:

**{
  "and": [
    {
      "some": [
        {
          "var": "Fruits"
        },
        {
          "if": [
            {
              "==": [
                {
                  "var": "Fruit"
                },
                "Apple"
              ]
            },
            {
              "==": [
                {
                  "var": "Fruit"
                },
                "Goa"
              ]
            }
          ]
        }
      ]
    },
    {
      "some": [
        {
          "var": "Veg"
        },
        {
          "==": [
            {
              "var": "Veg1"
            },
            "Cali"
          ]
        }
      ]
    }
  ]
}**

while comparing I am getting below exception:

'io.github.jamsesso.jsonlogic.evaluator.JsonLogicEvaluationException: first argument to some must be a valid array
	at io.github.jamsesso.jsonlogic.evaluator.expressions.ArrayHasExpression.evaluate(ArrayHasExpression.java:35)
	at io.github.jamsesso.jsonlogic.evaluator.JsonLogicEvaluator.evaluate(JsonLogicEvaluator.java:132)
	at io.github.jamsesso.jsonlogic.evaluator.JsonLogicEvaluator.evaluate(JsonLogicEvaluator.java:22)
	at io.github.jamsesso.jsonlogic.evaluator.expressions.LogicExpression.evaluate(LogicExpression.java:35)
	at io.github.jamsesso.jsonlogic.evaluator.JsonLogicEvaluator.evaluate(JsonLogicEvaluator.java:132)
	at io.github.jamsesso.jsonlogic.evaluator.JsonLogicEvaluator.evaluate(JsonLogicEvaluator.java:22)
	at io.github.jamsesso.jsonlogic.JsonLogic.apply(JsonLogic.java:90)'

Could you please help out  (SOME) is it bug? or Am I doing something wrong?

**Comment by bvarghese1** [comment]
@jamsesso I am also seeing the same issue when the arraylike field is null. This evaluation works fine in http://jsonlogic.com/
Here is another example:
Data:
```{"and":[{"some":[{"var":"ext"},{"in":[{"var":""},["docx"]]}]}]}```
JSONLogic:
```{"ext":null, "name":"TestDoc"}```

**Comment by bvarghese1** [comment]
Would it make sense to have an explicit null check before this https://github.com/jamsesso/json-logic-java/blob/master/src/main/java/io/github/jamsesso/jsonlogic/evaluator/expressions/ArrayHasExpression.java#L34 and remove the null check from isEligible? The null check can then return false.

**Comment by jamsesso** [comment]
@bvarghese1 That sounds like a reasonable solution to me 👍 are you comfortable making a PR?

**Comment by bvarghese1** [comment]
@jamsesso Sure. I can give it a shot.

**Comment by jamsesso** [comment]
Thanks! That is a big help. Let me know if you need any help.

**Comment by bvarghese1** [comment]
@jamsesso https://github.com/jamsesso/json-logic-java/pull/15
I was having issues with gradle. I had to update the descriptionUrl as follows:
```
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip
```
Let me know if you want me to update the distributionUrl as well.

**Comment by jamsesso** [comment]
Sure, that sounds good to me. I should spend some time getting this project up to date with the latest Gradle.
