### ISSUE TITLE
Getting value from Array by Index exception

### ISSUE THREAD

**Issue by iliecirciumaru** [jamsesso/json-logic-java#18]
### Description
According to [JSONLogic](https://jsonlogic.com/operations.html#var) specification following behaviour is expected:
```
jsonLogic.apply(
	{"var" : 1 },
	[ "apple", "banana", "carrot" ]
);
// "banana"
```
Note that index `1` or `"1"` should return same result

According to `JsonLogicEvaluator.evaluatePartialVariable`, I think was planned, that following expression returns `null`.

```
jsonLogic.apply(
	{"var" : "5" },
	[ "apple", "banana", "carrot" ]
);
// null
```

### Problem
If index asked equals to size of the array, then exception is thrown instead of `null` return.
```
jsonLogic.apply(
	{"var" : "3"},
	[ "apple", "banana", "carrot" ]
);
// throws IndexOutOfBoundsException
```

Problem in code `JsonLogicEvaluator.evaluatePartialVariable`: 
Current
```
if (index < 0 || index > list.size()) {
  return null;
}
```

Should be
```
if (index < 0 || index >= list.size()) {
  return null;
}
```

### Solution

Change in [JsonLogicEvaluator](https://github.com/jamsesso/json-logic-java/blob/master/src/main/java/io/github/jamsesso/jsonlogic/evaluator/JsonLogicEvaluator.java#L101): `index > list.size` ---> `index >= list.size`

**Comment by jamsesso** [comment]
@iliecirciumaru Version 1.0.6 was deployed with your changes. Thanks for contributing a fix!
