### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by jbaris** [jamsesso/json-logic-java#2]
Do you have plans to put this into a Maven public repo? It will allow us to quickly import and use this project. Thanks and regards!

**Comment by jamsesso** [comment]
I will try to get that done soon @jbaris, thanks for letting me know that there is some demand for it.

**Comment by bvarghese1** [comment]
@jamsesso Any timeline regarding publishing this project to the Maven repo?

**Comment by jamsesso** [comment]
I opened a ticket with Sonatype, waiting on approval to promote the first release: https://issues.sonatype.org/browse/OSSRH-47529

I'll reopen this issue for tracking progress.

**Comment by jamsesso** [comment]
@jbaris @bvarghese1 Here you go:

```
<dependency>
  <groupId>io.github.jamsesso</groupId>
  <artifactId>json-logic-java</artifactId>
  <version>1.0.0</version>
</dependency>
```

**Comment by bvarghese1** [comment]
@jamsesso Thanks a lot!

**Comment by jbaris** [comment]
@jamsesso Thank you very much!
