### ISSUE TITLE
Contains and startsWith

### ISSUE THREAD

**Issue by mattpal** [jamsesso/json-logic-java#24]
Hi - for a project I'm working on it looks like we might need two additional operations:

starts_with   (kind of like "in", but at beginning)
contains  (the opposite of "missing")

1. Is there an existing way to do those?
2. If not, would you accept a PR to add them?

**Comment by jamsesso** [comment]
@mattpal you can add custom operations to your JsonLogic object using the `addOperation` method:

```
jsonLogic.addOperation("greet", (args) -> "Hello, " + args[0] + "!");
```
