### ISSUE TITLE
How could this be equal

### ISSUE THREAD

**Issue by 0019** [jamsesso/json-logic-java#30]
`import io.github.jamsesso.jsonlogic.JsonLogic;
import io.github.jamsesso.jsonlogic.JsonLogicException;

public class RuleEngine {

    private final static JsonLogic jsonLogic = new JsonLogic();

    public static void main(String[] args) throws JsonLogicException {
        String expression = "{\"==\": [{\"var\": \"x.value\"}, {\"var\": \"y.value\"}]}";
        String data = "{\"x\": {\"value\": 0}, \"y\": {\"value\": 1}}";

        Boolean result = (Boolean)jsonLogic.apply(expression, data);
        if (result)
            System.out.println("equal");
    }

}
`

What did I miss? It's driving me crazy...

**Comment by 0019** [comment]
Well, if I specify the data in a map then it works:

`Map d = new HashMap<String, Integer>(){{
            put("x", 0);
            put("y", 1);
        }};`

Does it only take in map? How to use nested data then?

**Comment by grzegorz-taramina** [comment]
I'm having exactly the same problem. The library doesn't seem to support nested objects. Any plans to enhance it ?

**Comment by jamsesso** [comment]
It does support nested objects.

```
Map<String, String> nested = Collections.singletonMap("B", "C");
Map<String, Object> data = Collections.singletonMap("A", nested);
```

As JSON this is `{"A": {"B": "C"}}`.

If you have a JSON string as your data, try converting to an `Object` using `gson.fromJson`.
