### ISSUE TITLE
How to use `in` array operator with data?

### ISSUE THREAD

**Issue by pn** [jamsesso/json-logic-java#6]
I'm trying to use `in`operator with arrays. It works with inline data but I'm not able to make it work with data object.

```
assertEquals(true, jsonLogic.apply("""{"in": [1, [1, 2, 3]]}""", null)) // this works

val data1 = mapOf("value" to 1)
assertEquals(true, jsonLogic.apply("""{"in": [{"var": "value"}, [1, 2, 3]]}""", data1)) // does not work
val data2 = mapOf("list" to listOf(1, 2, 3))
assertEquals(true, jsonLogic.apply("""{"in": [1, {"var": "list"}]}""", data2)) // does not work
```

Am I doing something wrong? Or is it a bug?

**Comment by jamsesso** [comment]
Does it work on json-logic.com in the playground?

**Comment by pn** [comment]
Yes, both examples work there.

**Comment by pn** [comment]
Sample values for the playground:
Rule: `{"in": [1, {"var": "list"}]}`
Data: `{"list": [1,2,3]}`
is true

Rule: `{"in": [1, {"var": "list"}]}`
Data: `{"list": [5,2,3]}`
is false

**Comment by jamsesso** [comment]
Thanks for checking, I'll try to take a look at this soon.

**Comment by pn** [comment]
Looks like integer is evaluated as floating point and then:
```
ArrayLike(arguments.get(1)).contains(arguments.get(0));
```
gets  `1.0` and `[1, 2, 3]` and it doesn't match. So, this works:
```
val data2 = mapOf("list" to listOf(1.0, 2.0, 3.0))
assertEquals(true, jsonLogic.apply("""{"in": [1, {"var": "list"}]}""", data2))
```

**Comment by pn** [comment]
@jamsesso, do you have an idea how to fix it?

**Comment by jamsesso** [comment]
I haven't had a chance to look into it yet.

**Comment by jamsesso** [comment]
@pn Can you review the above PR?
