### ISSUE TITLE
Truthy on double.Nan returns True (instead of false)

### ISSUE THREAD

**Issue by patmonfort** [jamsesso/json-logic-java#9]
Hello,
While trying the 'truthy' method of JsonLogic (v1.0.2), we discover that calling this method with Double.NaN returns true instead of false. (https://developer.mozilla.org/en-US/docs/Glossary/Falsy) 
This seems to come the way 'Double' are checked in the 'truthy' method of JsonLogic.java. This method considers a Double as truthy if it's different to zero. Could you please add a check using Double.isNan((Number) value) also ? Thanks

**Comment by jamsesso** [comment]
@patmonfort Can you verify that the PR I put up fixes your issues?

**Comment by patmonfort** [comment]
@jamsesso hello, thanks a lot for your job and reactivity, those fixes are ok.
